
export default new Map([
["src/content/case-studies/folsom-psychology.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcase-studies%2Ffolsom-psychology.mdx&astroContentModuleFlag=true")],
["src/content/case-studies/lago.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcase-studies%2Flago.mdx&astroContentModuleFlag=true")],
["src/content/case-studies/sage-designing-an-ai-powered-chatbot.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcase-studies%2Fsage-designing-an-ai-powered-chatbot.mdx&astroContentModuleFlag=true")],
["src/content/case-studies/sprocket-app.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcase-studies%2Fsprocket-app.mdx&astroContentModuleFlag=true")],
["src/content/case-studies/subscription-cancellation.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcase-studies%2Fsubscription-cancellation.mdx&astroContentModuleFlag=true")],
["src/content/posts/ai-chatbots-customer-service-guide.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fai-chatbots-customer-service-guide.mdx&astroContentModuleFlag=true")],
["src/content/posts/beginner-friendly-advice-for-an-impactful-ux-portfolio.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fbeginner-friendly-advice-for-an-impactful-ux-portfolio.mdx&astroContentModuleFlag=true")],
["src/content/posts/breaking-the-config-seal---my-first-time-at-the-figma-conference.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fbreaking-the-config-seal---my-first-time-at-the-figma-conference.mdx&astroContentModuleFlag=true")],
["src/content/posts/how-relevant-are-user-personas-a-personal-story.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fhow-relevant-are-user-personas-a-personal-story.mdx&astroContentModuleFlag=true")],
["src/content/posts/how-to-apply-for-jobs-in-a-tough-market.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fhow-to-apply-for-jobs-in-a-tough-market.mdx&astroContentModuleFlag=true")],
["src/content/posts/how-to-collect-free-ux-survey-responses-in-24-hours.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fhow-to-collect-free-ux-survey-responses-in-24-hours.mdx&astroContentModuleFlag=true")],
["src/content/posts/how-to-conduct-effective-ux-interviews.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fhow-to-conduct-effective-ux-interviews.mdx&astroContentModuleFlag=true")],
["src/content/posts/how-to-create-jr-ux-ui-portfolio-presentations.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fhow-to-create-jr-ux-ui-portfolio-presentations.mdx&astroContentModuleFlag=true")],
["src/content/posts/how-to-think-about-accessibility-as-a-ux-designer.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fhow-to-think-about-accessibility-as-a-ux-designer.mdx&astroContentModuleFlag=true")],
["src/content/posts/my-ux-ui-journey.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fmy-ux-ui-journey.mdx&astroContentModuleFlag=true")],
["src/content/posts/obsidian-claude-code-figma-design-workflow.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fobsidian-claude-code-figma-design-workflow.mdx&astroContentModuleFlag=true")],
["src/content/posts/omg-is-ai-going-to-take-our-jobs-yes-no-maybe.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fomg-is-ai-going-to-take-our-jobs-yes-no-maybe.mdx&astroContentModuleFlag=true")],
["src/content/posts/the-productivity-hack-that-recruiting-gurus-on-linkedin-wont-give-you.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fthe-productivity-hack-that-recruiting-gurus-on-linkedin-wont-give-you.mdx&astroContentModuleFlag=true")]]);
		